PL/Controllers/AseguradoraController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class AseguradoraController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        
        {
            ML.Result result = BL.Aseguradora.GetAll();
            ML.Aseguradora aseguradora = new ML.Aseguradora();

            if (result.Correct)
            {
                aseguradora.Aseguradoras = result.Objects;
            }
            else
            {
                ViewBag.Message = "Error al cargar la informacion";
            }


            return View(aseguradora);
        }

        [HttpGet]
        public ActionResult Form(int? IdAseguradora) //se usa el int? para que acepte valores null
        {
            ML.Aseguradora aseguradora = new ML.Aseguradora(); //Se instancia aseguradora para poder asignar los usuarios
            aseguradora.Usuario = new ML.Usuario(); //Se inicializa aseguradora.Usuario

            ML.Usuario usuario = new ML.Usuario();

            ML.Result resultUsuarios = BL.Usuario.GetAll(usuario); //Se manda a llamar al metodo de GetAll Usuario para que tome en cuenta las opciones de la lista


            if (IdAseguradora == null)
            {
                aseguradora.Usuario.Usuarios = resultUsuarios.Objects;
                return View(aseguradora);
            }

            else
            {
                ML.Result result = BL.Aseguradora.GetById(IdAseguradora.Value);

              
                if (result.Correct)
                {
                    //Se tiene que hacer un unboxing del objeto que nos trajo el metodo de GEYBYID
                    aseguradora = (ML.Aseguradora)result.Object; //Se usa el object porque solo es 1 objeto 

                    aseguradora.Usuario.Usuarios = resultUsuarios.Objects; //ResultUsuarios trae todos los Usuarios es necesario especificar la ruta: aseguradora.Usuario.Usuarios


                }
                else
                {
                    ViewBag.Message = "Error al cargar la informacion";
                }
                return View(aseguradora);
            }
            return View(aseguradora);
        }

        [HttpPost]
        public ActionResult Form(ML.Aseguradora aseguradora) //se usa el int? para que acepte valores null
        {
            //ML.Usuario usuario = new ML.Usuario();

            if (aseguradora.IdAseguradora == 0)
            {
                ML.Result result = BL.Aseguradora.Add(aseguradora);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error:" + result.Message;
                }

            }

            else
            {
                ML.Result result = BL.Aseguradora.Update(aseguradora);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }

            return PartialView("Modal");
        }

        public ActionResult Delete(ML.Aseguradora aseguradora)
        {
            ML.Result result = BL.Aseguradora.Delate(aseguradora);
            if (result.Correct)
            {
                ViewBag.Message = result.Message;
            }
            else
            {
                ViewBag.Message = "Error:" + result.Message;
            }
            return PartialView("Modal");
        }
    }
}

PL/Views/Aseguradora/Form.cshtml
@model ML.Aseguradora
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Form</h2>
    <p>Aqui puede ver y actualizar los datos de la Aseguradora</p>

    <div class="row">
        <div class=" col-md-12">

            @using (Html.BeginForm("Form", "Aseguradora", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdAseguradora, new { @class = "hidden" }) @*LabelFor hace referencia a una etiqueta con texto*@

                            @Html.TextBoxFor(model => model.IdAseguradora, new { @class = "hidden form-control" }) @*Crea una caja de texto con el nombre que le indiquemos  y con un valor por defecto en el segundo parámetro.*@

                            @Html.ValidationMessageFor(model => model.IdAseguradora)

                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.NombreAseguradora)

                            @Html.TextBoxFor(model => model.NombreAseguradora, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.NombreAseguradora)

                        </div>

                    </div>
                   @* <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdUsuario)

                            @Html.TextBoxFor(model => model.IdUsuario, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.IdUsuario)

                        </div>

                    </div>*@
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Usuario.IdUsuario)

                            @Html.DropDownListFor(model => model.Usuario.IdUsuario, new SelectList(Model.Usuario.Usuarios, "IdUsuario", "NombreUsuario"), "Selecciona una opción", new { id = "ddlUsuario", @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Usuario.IdUsuario)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @*Se crea el boton de guardar*@

                            @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
                            @*Se crea el boton de regresar se regresa al metodo GetAll en el controlador de usuario*@
                        </div>

                    </div>

                </div>
            }

        </div>


    </div>

</div>

PL/Views/Aseguradora/GetAll.cshtml
@model ML.Aseguradora
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Aseguradora</h2>
    <p>Aqui podra ver los datos relacionados con la empresa asi como editar y eliminar</p>
</div>
    <div class=" row">
        <div style="float:right">
            @Html.ActionLink("Agregar", "Form", "Aseguradora", htmlAttributes: new { @class = "btn btn-success" }) @*Agregar un boton + *@
        </div>
    </div>



    <dir class=" row">
        <table class=" table table-responsive" id="tblAseg">
            <thead class="thead-dark">
                <tr>
                    @*<th>Hace referencia a las cabeceras de la tabla</th>*@
                    <th>Editar</th>
                    <th class=" d-none">IdAseguradora</th> @*se oculta el id del usuario ya que no es necesario el mostrarlo*@
                    <th>Nombre</th>
                    <th>Fecha de Creacion</th>
                    <th>Fecha de Modificacion</th>
                    <th class="d-none">Id Usuario</th>
                    <th>Nombre Usuario</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Aseguradora aseguradora in Model.Aseguradoras)
                {
                    <tr>
                        <td class="text-center"><a class="bi bi-pencil-square btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora})"></a></td>
                        <td class="d-none">@aseguradora.IdAseguradora</td>
                        <td>@aseguradora.NombreAseguradora</td> @*se concatena para que muestre todo junto*@
                        <td>@aseguradora.FechaCreacion</td>
                        <td>@aseguradora.FechaModificacion</td>
                        <td class="d-none">@aseguradora.IdUsuario</td>
                        <td>@aseguradora.NombreUsuario @aseguradora.ApellidoPaternoU @aseguradora.ApellidoMaternoU</td>
                        <td class="text-center"><a class="bi bi-file-earmark-x-fill btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>

                    </tr>

                }
            <tbody>
        </table>
    </dir>

@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblAseg').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
    </script>

}

PL/Views/Aseguradora/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>