PL/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class EmpleadoController : Controller
    {
            [HttpGet]
            public ActionResult GetAll()
            {
                ML.Empleado empleado = new ML.Empleado();
                ML.Result result = BL.Empleado.GetAll();

                if (result.Correct)
                {
                    empleado.Empleados = result.Objects;
                }
                else
                {
                    ViewBag.Message = "Error al cargar la informacion";
                }


                return View(empleado);
            }
        [HttpGet] //Verifica si el usuario viene null o con informacion
        public ActionResult Form(string? NumeroEmpleado) //se usa el int? para que acepte valores null
        {
            ML.Empleado empleado = new ML.Empleado(); //Se crea un nuevo empleado
            ML.Empresa empresa = new ML.Empresa();
            ML.Result resultEmpresa = BL.Empresa.GetAll(empresa);
            
            empleado.Empresa = new ML.Empresa();

            

            if (NumeroEmpleado == null)
            {
                empleado.Action = "Add";
                empleado.Empresa.Empresas = resultEmpresa.Objects;
                return View(empleado);
            }

            else
            {
                empleado.Action = "Update";
                //GET BY ID
                ML.Result result = BL.Empleado.GetById(NumeroEmpleado);

                if (result.Correct)
                {
                    //Se tiene que hacer un unboxing del objeto que nos trajo el metodo de GEYBYID este a su vez los muestra en la vista
                    empleado = (ML.Empleado)result.Object;// Unboxing
                    empleado.Empresa.Empresas = resultEmpresa.Objects; //ResultRol trae todos los Roles es necesario especificar la ruta: usuario.Rol.Roles

                    return View(empleado);
                }
                else
                {
                    ViewBag.Message = "Error al cargar la informacion";
                }
                
            }
            return View(empleado);
        }
        

        [HttpPost]
        public ActionResult Form(ML.Empleado empleado) //se usa el int? para que acepte valores null
        {
            IFormFile image = Request.Form.Files["ImagenData"];
            /*ML.Usuario usuariov = new ML.Usuario();*/ //Se instancia la clase usuario para poder asignar el Rol

            //valido si traigo imagen
            if (image != null)
            {
                //llamar al metodo que convierte a bytes la imagen
                byte[] ImagenBytes = ConvertToBytes(image);
                //convierto a base 64 la imagen y la guardo en la propiedad de imagen en el objeto alumno
                empleado.Foto = Convert.ToBase64String(ImagenBytes);
            }
            //empleado.NumeroEmpleado == "0"

            
                if (empleado.Action == "Add")
                {

                    ML.Result result = BL.Empleado.Add(empleado);

                if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error:" + result.Message;
                    }

                }

            else
            {
                    ML.Result result = BL.Empleado.Update(empleado);

                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error: " + result.Message;
                    }
                
            }

            return PartialView("Modal");
        }

        public ActionResult Delete(string NumeroEmpleado)
        {
            if (NumeroEmpleado != null)
            {   /*ML.Usuario usuario = new ML.Usuario();*/
                ML.Result result = BL.Empleado.DelateEF(NumeroEmpleado);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error:" + result.Message;
                }

            }

            return PartialView("Modal");
        }

        public byte[] ConvertToBytes(IFormFile Imagen)
        {
            using var fileStream = Imagen.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, bytes.Length);

            return bytes;
        }
    }
}

PL/Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        [HttpGet]
            public ActionResult GetAll()
            {
                ML.Empresa empresa = new ML.Empresa();
                ML.Result result = BL.Empresa.GetAll(empresa);

            if (result.Correct)
                {
                    empresa.Empresas = result.Objects;
                }
                else
                {
                    ViewBag.Message = "Error al cargar la informacion";
                }


                return View(empresa);
            }


        [HttpPost]
        public ActionResult GetAll(ML.Empresa empresa)
        {
            ML.Result result = BL.Empresa.GetAll(empresa);

            //ML.Result result = BL.Usuario.GetAll(usuario);
            if (result.Correct)
            {
                empresa.Empresas = result.Objects;
            }
            else
            {
                ViewBag.Message = "Error al cargar la informacion";
            }


            return View(empresa);
        }



        [HttpGet]
            public ActionResult Form(int? IdEmpresa) //se usa el int? para que acepte valores null
            {
                ML.Empresa empresa = new ML.Empresa();
                if (IdEmpresa == null)
                {
                return View(empresa);
                }

                else
                {
                    ML.Result result = BL.Empresa.GetById(IdEmpresa.Value);

                    //ML.Empresa empresa = new ML.Empresa();

                    if (result.Correct)
                    {
                        //Se tiene que hacer un unboxing del objeto que nos trajo el metodo de GEYBYID
                        empresa = (ML.Empresa)result.Object; //Se usa el object porque solo es 1 objeto 
                    }
                    else
                    {
                        ViewBag.Message = "Error al cargar la informacion";
                    }
                    return View(empresa);
                }
            }

            [HttpPost]
            public ActionResult Form(ML.Empresa empresa) //se usa el int? para que acepte valores null
            {
            
            IFormFile image = Request.Form.Files["ImagenData"];


            //valido si traigo imagen
            if (image != null)
            {
                //llamar al metodo que convierte a bytes la imagen
                byte[] LogoBytes = ConvertToBytes(image);
                //convierto a base 64 la imagen y la guardo en la propiedad de imagen en el objeto alumno
                empresa.Logo = Convert.ToBase64String(LogoBytes);
            }

            if (empresa.IdEmpresa == 0)
                {
                    ML.Result result = BL.Empresa.Add(empresa);
                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error:" + result.Message;
                    }

                }

                else
                {
                    ML.Result result = BL.Empresa.Update(empresa);

                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error: " + result.Message;
                    }
                }

                return PartialView("Modal");
            }

            public ActionResult Delete(ML.Empresa empresa)
            {
                ML.Result result = BL.Empresa.Delate(empresa);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error:" + result.Message;
                }
                return PartialView("Modal");
            }




        //JSON//

        public byte[] ConvertToBytes(IFormFile Imagen)
        {
            using var fileStream = Imagen.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, bytes.Length);

            return bytes;
        }  //COnvertir en un arreglo de bytes

    }
}

PL/Views/Empresa/Form.cshtml
@model ML.Empresa
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Form</h2>
    <p>Aqui puede ver y actualizar los datos de la empresa</p>

    <div class="row">
        <div class=" col-md-12">

            @using (Html.BeginForm("Form", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdEmpresa, new { @class = "hidden" }) @*LabelFor hace referencia a una etiqueta con texto*@

                            @Html.TextBoxFor(model => model.IdEmpresa, new { @class = "hidden form-control" }) @*Crea una caja de texto con el nombre que le indiquemos  y con un valor por defecto en el segundo parámetro.*@

                            @Html.ValidationMessageFor(model => model.IdEmpresa)

                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.NombreEmpresa)

                            @Html.TextBoxFor(model => model.NombreEmpresa, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.NombreEmpresa)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Telefono)

                            @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Telefono)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Email)

                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Email)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.DireccionWeb)

                            @Html.TextBoxFor(model => model.DireccionWeb, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.DireccionWeb)

                        </div>

                    </div>

                    <div class="row">
                        <div class=" offset-md-12">

                            @Html.LabelFor(model=> model.Logo)

                            <div class="input-group mb-3">
                                <input type="file" name="ImagenData" id="fileName" onchange="validateFileType(this), Previsualizar(this);">
                            </div>

                            @if (Model.Logo != null)
                            {

                                <img id="Img" src="data:image/*;base64,@Model.Logo" style="width:100px ; height:100px" />

                            }
                            else
                            {
                                <img id="Img" src="~/Imagen/NoFoto.jpg" style="width:100px ; height:100px" />

                            }

                            @Html.ValidationMessageFor(model => model.Logo)
                        </div>   @*Imagen*@
                        @Html.HiddenFor(model => model.Logo) @*Para no perder la imagen*@
                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @*Se crea el boton de guardar*@

                            @Html.ActionLink("Regresar", "GetAll", "Empresa", htmlAttributes: new { @class = "btn btn-danger" })
                            @*Se crea el boton de regresar se regresa al metodo GetAll en el controlador de usuario*@
                        </div>

                    </div>

                </div>
            }

        </div>


    </div>

</div>

@section Scripts
    {
    <script src="~/lib/jquery/dist/jquery.js"></script>


    <script type="text/javascript">
        function Previsualizar(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#Img').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);


            }
        }  /*Previsualizar la imagen*/

        function validateFileType() {
            var fileName = document.getElementById("fileName").value;
            var idxDot = fileName.lastIndexOf(".") + 1;
            var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
            if (extFile == "jpg" || extFile == "jpeg" || extFile == "png") {
                //TO DO
            } else {
                alert("Solo archivos jpg/jpeg y png son aceptados");
            }
        }  /*Validar el tipo de imagen*/

    </script>   @*Funciones de validacion *@


}

PL/Views/Empresa/GetAll.cshtml
@model ML.Empresa
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Empresa</h2>
    <p>Aqui podra ver los datos relacionados con la empresa asi como editar y eliminar</p>
</div>

<div style="float:right;">
    @Html.ActionLink("Agregar", "Form", "Empresa", htmlAttributes: new { @class = "btn btn-success" })
</div>

@using (Html.BeginForm("GetAll", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p>Busqueda avanzada</p>

    <div class="col-md-3">
        @Html.TextBoxFor(model => model.NombreEmpresa, new { @class = "form-control", @placeholder = "Nombre" })
    </div>

    <div class="col-md-3">
        <input type="submit" value="Buscar" class="btn btn-success" />
    </div>
}


    <dir class=" row">
        <table class=" table table-responsive" id="tblEmpresa">
            <thead class="thead-dark">
                <tr>
                    @*<th>Hace referencia a las cabeceras de la tabla</th>*@
                    <th>Editar</th>
                    <th class=" d-none">IdEmpresa</th> @*se oculta el id del usuario ya que no es necesario el mostrarlo*@
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Email</th>
                    <th>Direccion Web</th>
                    <th>Logo</th>

                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Empresa empresa in Model.Empresas)
                {
                    <tr>
                        <td class="text-center"><a class="bi bi-pencil-square btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Empresa", new { IdEmpresa = empresa.IdEmpresa})"></a></td>
                        <td class="d-none">@empresa.IdEmpresa</td>
                        <td>@empresa.NombreEmpresa</td> @*se concatena para que muestre todo junto*@
                        <td>@empresa.Telefono</td>
                        <td>@empresa.Email</td>
                        <td>@empresa.DireccionWeb</td>

                    @if (empresa.Logo != null)
                    {
                        <td><img src="data:image/*;base64, @empresa.Logo" style="height:100px; width:100px;" /></td>
                    }
                    else
                    {
                        <td><img id="Img" src="~/Imagen/NoFoto.jpg" style=" height:100px; width:100px;" /></td>
                    }



                        <td class="text-center"><a class="bi bi-file-earmark-x-fill btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Empleado", new { IdEmpresa = empresa.IdEmpresa })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                    </tr>
                }
            <tbody>
        </table>
    </dir>

@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblEmpresa').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
    </script>

}

PL/Views/Empresa/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Empresa", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>